[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "endless-prototype"
version = "0.1.0"
dependencies = [
    'aiomqtt',
]

[project.scripts]
run-components = "endless.framework.runner:main"
